pipeline {
    agent any
    stages {
        stage('app1_dev') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }
            steps {
                echo "Hello, ${PERSON}, nice to meet you."
                echo "Value of string parameter ${STRING_PARAM}"
                echo "Value of integer parameter ${INT_PARAM}"

            }
        }
    }
}
